### ISSUE TITLE
train_large.sh

### ISSUE THREAD

**Issue by thankuuu** [BriansIDP/WhisperBiasing#6]
I encountered the following error while running your code:

Traceback (most recent call last):
File "train.py", line 70, in <module>
decodetask = whisper.decoding.DecodingTask(model, options)
File "/root/autodl-tmp/WhisperBiasing/whisper/decoding.py", line 514, in init
self.sot_index: int = self.initial_tokens.index(tokenizer.sot)
ValueError: tuple.index(x): x not in tuple

 I have verified the content of tokenizer, but I am still unable to resolve this error.
Could you please provide some guidance on how to address this issue?    Thank you for your time and assistance.

**Comment by BriansIDP** [comment]
Hi. Thank you for your question and sorry for replying late. I have not come across this error before and I suspect this is something related to Whisper itself rather than my added code. Please let me know if there is any update on this issue.
